### ISSUE TITLE
the boost::exception error

### ISSUE THREAD

**Issue by SISTMrL** [jbehley/voxelizer#11]
when i run the voxelizer, the problem encountered is shown as below:

![image](https://user-images.githubusercontent.com/47938053/232480439-6f94ef71-5816-4d04-9cbd-e1b6f649125c.png)

here is my folder files:
calib.txt
![image](https://user-images.githubusercontent.com/47938053/232479613-ea76a0c9-ae7e-4ee5-a487-fa8c46e73e7a.png)
poses.txt
![image](https://user-images.githubusercontent.com/47938053/232479734-01606a22-8e39-4813-adc8-6621c04b29d1.png)
times.txt
![image](https://user-images.githubusercontent.com/47938053/232479890-14b60f94-0cb9-489a-83ae-20dd66ce2ebf.png)
velodyne
![image](https://user-images.githubusercontent.com/47938053/232479952-113e5953-b922-4be7-babd-2c4a489e9d95.png)

**Comment by jbehley** [comment]
sorry for the late reply.

ensure that you have "en_us" or a similar locale that interprets the "." as separator. In some languages (such as German, we write decimals as "3,14159265359" instead of "3.14159265359"); thus the lexical cast respect this and cannot interpret the "1.4" as floating point value.

hope that solves your problem.
